# -*- coding: utf-8 -*-
"""Практикум

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Isc876nw057LdNSTkC2vjHiKmmDS6fQ
"""

import tkinter as tk
from tkinter import ttk
import random

class RainDrop:
    def __init__(self, canvas, width, height):
        self.canvas = canvas
        self.width = width
        self.height = height

        # Случайная глубина для 3D эффекта (0 - ближние, 1 - дальние)
        self.depth = random.uniform(0.2, 1.0)

        # Размер и скорость зависят от глубины
        self.size = max(2, int(10 * self.depth))
        self.speed = max(1, int(8 * (1 - self.depth * 0.5)))

        # Начальная позиция
        self.x = random.randint(0, width)
        self.y = random.randint(-100, 0)

        # Фиолетовый цвет с разной интенсивностью для глубины
        color_intensity = int(150 + 100 * (1 - self.depth))
        self.color = f'#{color_intensity:02x}00{color_intensity:02x}'

        # Создание овальной капли
        self.id = canvas.create_oval(
            self.x, self.y,
            self.x + self.size,
            self.y + self.size * 1.5,
            fill=self.color, outline=""
        )

    def move(self):
        self.y += self.speed
        self.canvas.move(self.id, 0, self.speed)

        # Если капля ушла за нижнюю границу, пересоздаём её сверху
        if self.y > self.height:
            self.reset()

    def reset(self):
        self.y = random.randint(-100, -20)
        self.x = random.randint(0, self.width)
        self.canvas.coords(
            self.id,
            self.x, self.y,
            self.x + self.size,
            self.y + self.size * 1.5
        )

class RainAnimation:
    def __init__(self, root):
        self.root = root
        self.root.title("3D Капли с регулируемой плотностью")

        # Настройки экрана
        self.width = 800
        self.height = 600

        # Плотность капель
        self.drop_density = 100

        # Создание холста
        self.canvas = tk.Canvas(
            root,
            width=self.width,
            height=self.height,
            bg='black'
        )
        self.canvas.pack()

        # Создание ползунка для плотности
        self.create_density_slider()

        # Создание капель
        self.drops = []
        self.create_drops()

        # Запуск анимации
        self.animate()

    def create_density_slider(self):
        """Создает ползунок для регулировки плотности капель"""
        slider_frame = tk.Frame(self.root)
        slider_frame.pack(pady=10)

        tk.Label(slider_frame, text="Плотность капель:").pack(side=tk.LEFT)

        self.density_var = tk.IntVar(value=self.drop_density)
        self.density_slider = ttk.Scale(
            slider_frame,
            from_=20,
            to=800,
            orient=tk.HORIZONTAL,
            variable=self.density_var,
            command=self.on_density_change,
            length=300
        )
        self.density_slider.pack(side=tk.LEFT, padx=10)

        self.density_label = tk.Label(slider_frame, text=str(self.drop_density))
        self.density_label.pack(side=tk.LEFT)

    def on_density_change(self, event=None):
        """Обработчик изменения ползунка плотности"""
        new_density = int(self.density_var.get())
        self.density_label.config(text=str(new_density))

        # Обновляем плотность (изменения применятся при следующем reset() капель)
        self.drop_density = new_density

    def create_drops(self):
        """Создает начальный набор капель"""
        for _ in range(self.drop_density):
            self.drops.append(RainDrop(self.canvas, self.width, self.height))

    def update_drops_count(self):
        """Обновляет количество капель в соответствии с текущей плотностью"""
        current_count = len(self.drops)

        if current_count < self.drop_density:
            # Нужно добавить капли
            for _ in range(self.drop_density - current_count):
                self.drops.append(RainDrop(self.canvas, self.width, self.height))

        elif current_count > self.drop_density:
            # Нужно удалить лишние капли
            for _ in range(current_count - self.drop_density):
                if self.drops:  # Проверяем, что список не пустой
                    drop = self.drops.pop()  # Удаляем последнюю каплю
                    self.canvas.delete(drop.id)  # Удаляем с холста

    def animate(self):
        # Обновляем количество капель если плотность изменилась
        self.update_drops_count()

        # Двигаем все капли
        for drop in self.drops:
            drop.move()

        # Планируем следующий кадр
        self.root.after(30, self.animate)

# Запуск программы
if __name__ == "__main__":
    root = tk.Tk()
    app = RainAnimation(root)
    root.mainloop()